# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
defaults:
  run:
   working-directory: ./frontend
jobs:
 build:
    runs-on: ubuntu-latest
    name: Node ${{ matrix.node }} sample
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install and build
      run: 
        npm i
        cd src
        npm i 
        npm run build
